import type { RuleVersion } from "@/lib/types";

export const ruleVersions: RuleVersion[] = [
  {
    id: "rule-ifi-simplified-2026-v1",
    ruleSet: "ifi",
    version: "IFI-2026.03",
    title: "IFI simplifié : résidence principale, immobilier taxable et dette immobilière",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-ifi-2026"],
  },
  {
    id: "rule-ifi-complete-2026-v2",
    ruleSet: "ifi",
    version: "IFI-2026.05-V2",
    title: "IFI complet V2 : barème, décote, plafonnement, détention directe et dettes",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-ifi-2026"],
  },
  {
    id: "rule-transmission-checklist-2026-v1",
    ruleSet: "transmission",
    version: "2026.1-demo",
    title: "Transmission familiale : checklist professionnelle non chiffrée",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-legifrance-code-civil-transmission"],
  },
  {
    id: "rule-e-invoicing-readiness-2026-v1",
    ruleSet: "facturation-electronique",
    version: "2026.1-demo",
    title: "Facturation électronique : score de préparation TPE/PME",
    effectiveFrom: "2026-09-01",
    status: "active",
    evidenceSourceIds: ["src-impots-facturation-electronique-2026", "src-aife-facturation-electronique"],
  },
  {
    id: "rule-rgpd-dpia-demo-2026-v1",
    ruleSet: "rgpd",
    version: "2026.1-demo",
    title: "RGPD : signalement AIPD recommandé pour données patrimoniales",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-cnil-aipd"],
  },
  {
    id: "rule-donation-usufruit-2026-v1",
    ruleSet: "donation",
    version: "2026.1-pilot",
    title: "Donation et demembrement : valorisation indicative usufruit/nue-propriete",
    effectiveFrom: "2026-01-01",
    status: "draft",
    evidenceSourceIds: ["src-impots-donation-usufruit", "src-legifrance-code-civil-transmission"],
  },
  {
    id: "rule-plus-value-immobiliere-2026-v1",
    ruleSet: "plus-value",
    version: "2026.1-pilot",
    title: "Plus-value immobiliere : structure de calcul avant abattements detailles",
    effectiveFrom: "2026-01-01",
    status: "archived",
    evidenceSourceIds: ["src-bofip-plus-value-immobiliere"],
  },
  {
    id: "rule-plus-value-immobiliere-2026-v2",
    ruleSet: "plus-value",
    version: "PV-IMMO-2026.06-V2",
    title: "Plus-value immobilière V2 : forfaits 7,5 %/15 %, abattements exacts et arrondi officiel",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: ["src-bofip-plus-value-immobiliere", "src-impots-2048-imm-2026"],
  },
  {
    id: "rule-dmtg-bareme-2026-v1",
    ruleSet: "transmission",
    version: "DMTG-2026.06-V1",
    title: "DMTG art. 777 : barèmes multi-liens, abattements 779/790 et rappel fiscal 15 ans",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: ["src-impots-dmtg-bareme-2026"],
  },
  {
    id: "rule-demembrement-669-2026-v1",
    ruleSet: "donation",
    version: "DEMEMBREMENT-2026.06-V1",
    title: "Démembrement art. 669 : barème viager et usufruit temporaire 23 %/décennie",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: ["src-legifrance-cgi-669-2026", "src-impots-dmtg-bareme-2026"],
  },
  {
    id: "rule-ir-bareme-2026-v1",
    ruleSet: "ir-bareme",
    version: "IR-BAREME-2026.06-V1",
    title: "IR 2026 : barème progressif, quotient familial plafonné, décote, CEHR et CDHR",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: [
      "src-service-public-bareme-ir-2026",
      "src-economie-decote-ir-2026",
      "src-economie-cdhr-2026",
    ],
  },
  {
    id: "rule-pfu-arbitrage-2026-v1",
    ruleSet: "pfu-arbitrage",
    version: "PFU-ARBITRAGE-2026.06-V1",
    title: "PFU 31,4 % vs barème : abattements 40 %/50 %/65 %, PS 18,6 % et CSG déductible",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-pfu-2026", "src-legifrance-lfss-2026-ps-capital"],
  },
  {
    id: "rule-sci-arbitrage-2026-v1",
    ruleSet: "sci",
    version: "2026.1-pilot",
    title: "Arbitrage detention directe / SCI : flux et points de revue",
    effectiveFrom: "2026-01-01",
    status: "archived",
    evidenceSourceIds: ["src-legifrance-code-civil-transmission"],
  },
  {
    id: "rule-sci-arbitrage-2026-v2",
    ruleSet: "sci",
    version: "SCI-IR-IS-2026.06-V2",
    title: "SCI IR vs IS : foncier net, amortissements, IS et plus-value de sortie",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: ["src-bofip-sci-is-2026", "src-service-public-is-taux-2026"],
  },
  {
    id: "rule-der-2026-v1",
    ruleSet: "cif-orias",
    version: "DER-2026.06-V1",
    title: "DER : statuts, ORIAS, association, rémunération et liens capitalistiques obligatoires",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: ["src-amf-rg-325-5-2026", "src-legifrance-cmf-l541-8-1-2026", "src-amf-cif-orias-2026"],
  },
  {
    id: "rule-lettre-mission-2026-v1",
    ruleSet: "cif-orias",
    version: "LETTRE-MISSION-2026.06-V1",
    title: "Lettre de mission : objet, périmètre, délai obligatoire et honoraires",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: ["src-cncgp-lettre-mission-2026"],
  },
  {
    id: "rule-kyc-profil-risque-2026-v1",
    ruleSet: "mif2-dda",
    version: "KYC-2026.06-V1",
    title: "KYC MIF 2/DDA : connaissance, capacité de perte, tolérance, durabilité, horizon",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: ["src-amf-mif2-adequation", "src-amf-durabilite-2022"],
  },
  {
    id: "rule-lcb-ft-scoring-2026-v1",
    ruleSet: "lcb-ft",
    version: "LCB-FT-2026.06-V1",
    title: "Scoring LCB-FT : PPE, pays, origine des fonds, bénéficiaire effectif",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: ["src-tracfin-lignes-directrices-2026", "src-eurlex-aml-2015-849", "src-amf-lcb-ft-2021"],
  },
  {
    id: "rule-signature-demo-2026-v1",
    ruleSet: "documents-cabinet",
    version: "SIGNATURE-2026.06-V1",
    title: "Signature simulée niveau SES : hash, horodatage et archivage audit (eIDAS)",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: ["src-eurlex-eidas-910-2014"],
  },
  {
    id: "rule-pages-legales-2026-v1",
    ruleSet: "rgpd",
    version: "PAGES-LEGALES-2026.06-V1",
    title: "Pages légales : mentions, CGU et politique de confidentialité de la démo",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: ["src-cnil-rgpd-privacy-by-design"],
  },
  {
    id: "rule-agregation-demo-2026-v1",
    ruleSet: "bank-import",
    version: "AGREGATION-2026.06-V1",
    title: "Agrégation Powens/DSP2 simulée : consentement, SCA et rapprochement manuel",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: ["src-acpr-dsp2-api-2025", "src-eurlex-sca-2018-389"],
  },
  {
    id: "rule-projections-2026-v1",
    ruleSet: "sci",
    version: "PROJECTIONS-2026.06-V1",
    title: "Projections patrimoniales : capitalisation déterministe par catégorie (hypothèses internes)",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: ["src-interne-hypotheses-projection-2026"],
  },
  {
    id: "rule-calendrier-fiscal-2026-v1",
    ruleSet: "succession",
    version: "CALENDRIER-2026.06-V1",
    title: "Calendrier fiscal du dossier : 2042/2044, 2072, 2065, IFI, CFE, Dutreil, taxe holding",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: ["src-impots-calendrier-fiscal-2026"],
  },
  {
    id: "rule-compta-sci-2026-v1",
    ruleSet: "sci",
    version: "COMPTA-SCI-2026.06-V1",
    title: "Comptabilité SCI : classification 6/7/28/455 vers 2072 (IR) et 2065 (IS)",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: [
      "src-impots-liasse-2072-2026",
      "src-impots-liasse-2065-2026",
      "src-pennylane-api-v2-2026",
    ],
  },
  {
    id: "rule-is-bareme-2026-v1",
    ruleSet: "is",
    version: "IS-2026.06-V1",
    title: "IS 2026 : taux normal 25 %, taux réduit 15 % PME et contribution sociale 3,3 %",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-is-taux-2026"],
  },
  {
    id: "rule-exit-tax-2026-v1",
    ruleSet: "exit-tax",
    version: "EXIT-TAX-2026.06-V1",
    title: "Exit tax art. 167 bis : seuils 800 k€ / 50 %, sursis et dégrèvement",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-legifrance-cgi-167-bis-2026"],
  },
  {
    id: "rule-ai-governance-2026-v1",
    ruleSet: "ai-governance",
    version: "2026.1-pilot",
    title: "IA controlee : citations, abstention et validation humaine",
    effectiveFrom: "2026-08-02",
    status: "draft",
    evidenceSourceIds: ["src-eu-ai-act-transparency", "src-cnil-aipd"],
  },
  {
    id: "rule-ir-pfu-cdhr-2026-v2",
    ruleSet: "ir-pfu-cdhr",
    version: "IR-PFU-CDHR-2026.05-V2",
    title: "IR, PFU 30/31,4 % et CDHR : pré-diagnostic dirigeant",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-pfu-2026", "src-economie-cdhr-2026"],
  },
  {
    id: "rule-dutreil-2026-v2",
    ruleSet: "dutreil",
    version: "DUTREIL-2026.05-V2",
    title: "Pacte Dutreil LF 2026 : éligibilité, abattement et exclusions à valider",
    effectiveFrom: "2026-02-21",
    status: "archived",
    evidenceSourceIds: ["src-legifrance-dutreil-2026"],
  },
  {
    id: "rule-dutreil-2026-v3",
    ruleSet: "dutreil",
    version: "DUTREIL-2026.06-V3",
    title: "Pacte Dutreil V3 : chaînage DMTG, économie vs sans pacte, réduction 790 I abrogée",
    effectiveFrom: "2026-06-11",
    status: "active",
    evidenceSourceIds: [
      "src-legifrance-dutreil-2026",
      "src-impots-dmtg-bareme-2026",
      "src-bofip-dmtg-reduction-790-2026",
    ],
  },
  {
    id: "rule-assurance-vie-990i-757b-2026-v1",
    ruleSet: "assurance-vie",
    version: "AV-990I-757B-2026.06-V1",
    title: "Assurance-vie au décès : 990 I (152 500 €, 20/31,25 %) et 757 B (30 500 €)",
    effectiveFrom: "2026-01-01",
    status: "draft",
    evidenceSourceIds: ["src-bofip-tcas-aut-60-2026", "src-impots-dmtg-bareme-2026"],
  },
  {
    id: "rule-apport-cession-2026-v2",
    ruleSet: "apport-cession",
    version: "APPORT-CESSION-2026.05-V2",
    title: "Apport-cession 150-0 B ter : réinvestissement 70 %, délai et conservation",
    effectiveFrom: "2026-02-21",
    status: "active",
    evidenceSourceIds: ["src-legifrance-apport-cession-2026"],
  },
  {
    id: "rule-holding-tax-2026-v2",
    ruleSet: "holding-tax",
    version: "HOLDING-TAX-2026.05-V2",
    title: "Taxe holding patrimoniale art. 235 ter C : critères cumulés et assiette",
    effectiveFrom: "2026-02-21",
    status: "active",
    evidenceSourceIds: ["src-legifrance-holding-tax-2026"],
  },
  {
    id: "rule-documents-cabinet-2026-v2",
    ruleSet: "documents-cabinet",
    version: "DOC-CABINET-2026.05-V2",
    title: "Documents cabinet : DER, FIL, lettre de mission et rapport d'adéquation",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-amf-mif2-adequation", "src-cnil-aipd"],
  },
  {
    id: "rule-pea-withdrawal-2026-v1",
    ruleSet: "pea",
    version: "PEA-2026.06-V1",
    title: "PEA : retrait après cinq ans, IR et prélèvements sociaux à distinguer",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: ["src-service-public-pea-2026"],
  },
  {
    id: "rule-per-deduction-2026-v1",
    ruleSet: "per",
    version: "PER-2026.06-V1",
    title: "PER : plafond disponible, reliquats et déduction utilisée",
    effectiveFrom: "2026-06-04",
    status: "archived",
    evidenceSourceIds: ["src-service-public-per-deduction-2026", "src-impots-epargne-retraite-2026"],
  },
  {
    id: "rule-per-deduction-2026-v2",
    ruleSet: "per",
    version: "PER-2026.06-V2",
    title: "PER 2026 : plafonds calculés 37 680/88 911 €, report 5 ans, blocage 70 ans, économie TMI",
    effectiveFrom: "2026-06-11",
    status: "draft",
    evidenceSourceIds: [
      "src-service-public-per-deduction-2026",
      "src-impots-epargne-retraite-2026",
      "src-legifrance-pass-2026",
    ],
  },
  {
    id: "rule-bank-import-demo-2026-v1",
    ruleSet: "bank-import",
    version: "BANK-IMPORT-DEMO-2026.06-V1",
    title: "Import bancaire simulé : consentement, SCA, normalisation et alertes",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: ["src-eurlex-sca-2018-389", "src-banque-france-sca-2022", "src-eurlex-aml-2015-849"],
  },
  {
    id: "rule-manual-review-complexity-2026-v1",
    ruleSet: "dac6-dac7",
    version: "MANUAL-REVIEW-2026.06-V1",
    title: "Revue manuelle : structures étrangères, flux transfrontières et bénéficiaires effectifs",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: ["src-eurlex-dac6-2018-822", "src-eurlex-dac7-2021-514", "src-eurlex-aml-2015-849"],
  },
  {
    id: "rule-succession-checklist-2026-v1",
    ruleSet: "succession",
    version: "SUCCESSION-2026.06-V24",
    title: "Succession simple : checklist, actif brut, notaire et paiement a verifier",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: [
      "src-service-public-succession-declaration-2025",
      "src-service-public-succession-rights-2024",
      "src-service-public-rapport-fiscal-succession-2025",
    ],
  },
  {
    id: "rule-per-early-exit-primary-home-2026-v1",
    ruleSet: "per-exit",
    version: "PER-EXIT-2026.06-V24",
    title: "PER : sortie anticipee residence principale, versements et gains a distinguer",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: ["src-service-public-per-release-2025", "src-bofip-per-fiscal-regime-2026"],
  },
  {
    id: "rule-succession-liquidity-stress-2026-v1",
    ruleSet: "liquidity-stress",
    version: "LIQUIDITY-STRESS-2026.06-V24",
    title: "Stress test succession : droits estimes, cash disponible et alerte deficit",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: [
      "src-service-public-succession-declaration-2025",
      "src-service-public-succession-rights-2024",
    ],
  },
  {
    id: "rule-product-adequacy-demo-2026-v1",
    ruleSet: "product-adequacy",
    version: "ADEQUACY-2026.06-V24",
    title: "Adequation produit simulee : horizon, risque, durabilite et marche cible sans recommandation",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: ["src-amf-mif2-adequation", "src-amf-cif-orias-2026", "src-cnil-profiling-automated-decision"],
  },
  {
    id: "rule-regulatory-controls-2026-v1",
    ruleSet: "cif-orias",
    version: "REG-CONTROLS-2026.06-V24",
    title: "Controles natifs : RGPD, CIF, LCB-FT, DORA et DSP2 en mode demo",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: [
      "src-amf-cif-orias-2026",
      "src-amf-lcb-ft-2021",
      "src-cnil-rgpd-privacy-by-design",
      "src-acpr-dora-2026",
      "src-acpr-dsp2-api-2025",
    ],
  },
  {
    id: "rule-cyber-hygiene-demo-2026-v1",
    ruleSet: "cyber",
    version: "CYBER-DEMO-2026.06-V24",
    title: "Cyber et stockage : hygiene, sauvegarde et absence de stockage sensible en V2.4",
    effectiveFrom: "2026-06-04",
    status: "draft",
    evidenceSourceIds: ["src-anssi-hygiene-2017", "src-anssi-backup-2023"],
  },
];

export function getRuleVersion(id: string) {
  return ruleVersions.find((rule) => rule.id === id);
}
