import type { RuleVersion } from "@/lib/types";

export const ruleVersions: RuleVersion[] = [
  {
    id: "rule-ifi-simplified-2026-v1",
    ruleSet: "ifi",
    version: "IFI-2026.03",
    title: "IFI simplifié : résidence principale, immobilier taxable et dette immobilière",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-ifi-2026"],
  },
  {
    id: "rule-ifi-complete-2026-v2",
    ruleSet: "ifi",
    version: "IFI-2026.05-V2",
    title: "IFI complet V2 : barème, décote, plafonnement, détention directe et dettes",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-ifi-2026"],
  },
  {
    id: "rule-transmission-checklist-2026-v1",
    ruleSet: "transmission",
    version: "2026.1-demo",
    title: "Transmission familiale : checklist professionnelle non chiffrée",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-legifrance-code-civil-transmission"],
  },
  {
    id: "rule-e-invoicing-readiness-2026-v1",
    ruleSet: "facturation-electronique",
    version: "2026.1-demo",
    title: "Facturation électronique : score de préparation TPE/PME",
    effectiveFrom: "2026-09-01",
    status: "active",
    evidenceSourceIds: ["src-impots-facturation-electronique-2026", "src-aife-facturation-electronique"],
  },
  {
    id: "rule-rgpd-dpia-demo-2026-v1",
    ruleSet: "rgpd",
    version: "2026.1-demo",
    title: "RGPD : signalement AIPD recommandé pour données patrimoniales",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-cnil-aipd"],
  },
  {
    id: "rule-donation-usufruit-2026-v1",
    ruleSet: "donation",
    version: "2026.1-pilot",
    title: "Donation et demembrement : valorisation indicative usufruit/nue-propriete",
    effectiveFrom: "2026-01-01",
    status: "draft",
    evidenceSourceIds: ["src-impots-donation-usufruit", "src-legifrance-code-civil-transmission"],
  },
  {
    id: "rule-plus-value-immobiliere-2026-v1",
    ruleSet: "plus-value",
    version: "2026.1-pilot",
    title: "Plus-value immobiliere : structure de calcul avant abattements detailles",
    effectiveFrom: "2026-01-01",
    status: "draft",
    evidenceSourceIds: ["src-bofip-plus-value-immobiliere"],
  },
  {
    id: "rule-sci-arbitrage-2026-v1",
    ruleSet: "sci",
    version: "2026.1-pilot",
    title: "Arbitrage detention directe / SCI : flux et points de revue",
    effectiveFrom: "2026-01-01",
    status: "draft",
    evidenceSourceIds: ["src-legifrance-code-civil-transmission"],
  },
  {
    id: "rule-ai-governance-2026-v1",
    ruleSet: "ai-governance",
    version: "2026.1-pilot",
    title: "IA controlee : citations, abstention et validation humaine",
    effectiveFrom: "2026-08-02",
    status: "draft",
    evidenceSourceIds: ["src-eu-ai-act-transparency", "src-cnil-aipd"],
  },
  {
    id: "rule-ir-pfu-cdhr-2026-v2",
    ruleSet: "ir-pfu-cdhr",
    version: "IR-PFU-CDHR-2026.05-V2",
    title: "IR, PFU 30/31,4 % et CDHR : pré-diagnostic dirigeant",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-service-public-pfu-2026", "src-economie-cdhr-2026"],
  },
  {
    id: "rule-dutreil-2026-v2",
    ruleSet: "dutreil",
    version: "DUTREIL-2026.05-V2",
    title: "Pacte Dutreil LF 2026 : éligibilité, abattement et exclusions à valider",
    effectiveFrom: "2026-02-21",
    status: "active",
    evidenceSourceIds: ["src-legifrance-dutreil-2026"],
  },
  {
    id: "rule-apport-cession-2026-v2",
    ruleSet: "apport-cession",
    version: "APPORT-CESSION-2026.05-V2",
    title: "Apport-cession 150-0 B ter : réinvestissement 70 %, délai et conservation",
    effectiveFrom: "2026-02-21",
    status: "active",
    evidenceSourceIds: ["src-legifrance-apport-cession-2026"],
  },
  {
    id: "rule-holding-tax-2026-v2",
    ruleSet: "holding-tax",
    version: "HOLDING-TAX-2026.05-V2",
    title: "Taxe holding patrimoniale art. 235 ter C : critères cumulés et assiette",
    effectiveFrom: "2026-02-21",
    status: "active",
    evidenceSourceIds: ["src-legifrance-holding-tax-2026"],
  },
  {
    id: "rule-documents-cabinet-2026-v2",
    ruleSet: "documents-cabinet",
    version: "DOC-CABINET-2026.05-V2",
    title: "Documents cabinet : DER, FIL, lettre de mission et rapport d'adéquation",
    effectiveFrom: "2026-01-01",
    status: "active",
    evidenceSourceIds: ["src-amf-mif2-adequation", "src-cnil-aipd"],
  },
];

export function getRuleVersion(id: string) {
  return ruleVersions.find((rule) => rule.id === id);
}
