import type { Asset, Household, Liability } from "@/lib/types";

export const demoAssets: Asset[] = [
  {
    id: "asset-cash",
    label: "Liquidités",
    category: "liquidity",
    envelope: "liquidites",
    value: 220_000,
    dataQuality: {
      status: "supporting_document_received",
      supportingDocumentId: "doc-tax-notice-2025",
      expectedAction: "Rapprocher avec les derniers relevés bancaires.",
      validationStatus: "pending",
    },
  },
  {
    id: "asset-cto",
    label: "Compte-titres",
    category: "financial",
    envelope: "cto",
    value: 480_000,
    dataQuality: {
      status: "user_declared",
      expectedAction: "Demander le relevé de compte-titres au 31/12.",
      validationStatus: "not_started",
    },
  },
  {
    id: "asset-pea",
    label: "PEA",
    category: "financial",
    envelope: "pea",
    value: 140_000,
    dataQuality: {
      status: "user_declared",
      expectedAction: "Collecter le relevé PEA et l'ancienneté du plan.",
      validationStatus: "not_started",
    },
  },
  {
    id: "asset-life-insurance",
    label: "Assurance-vie",
    category: "insurance",
    envelope: "assurance-vie",
    value: 350_000,
    dataQuality: {
      status: "estimated",
      supportingDocumentId: "doc-life-insurance",
      expectedAction: "Vérifier les contrats et clauses bénéficiaires.",
      validationStatus: "not_started",
    },
  },
  {
    id: "asset-main-residence",
    label: "Résidence principale",
    category: "real-estate",
    envelope: "immobilier-direct",
    value: 900_000,
    ifiKind: "main-residence",
    acquisitionDate: "2014-06-12",
    acquisitionValue: 680_000,
    isDirectlyHeld: true,
    dataQuality: {
      status: "estimated",
      supportingDocumentId: "doc-family-record",
      expectedAction: "Obtenir une estimation notariale ou avis de valeur récent.",
      validationStatus: "pending",
    },
  },
  {
    id: "asset-rental",
    label: "Immobilier locatif",
    category: "real-estate",
    envelope: "immobilier-direct",
    value: 600_000,
    ifiKind: "rental",
    acquisitionDate: "2017-03-20",
    acquisitionValue: 420_000,
    isDirectlyHeld: true,
    dataQuality: {
      status: "user_declared",
      supportingDocumentId: "doc-loan-contracts",
      expectedAction: "Rattacher titres de propriété, bail et capital restant dû.",
      validationStatus: "pending",
    },
  },
  {
    id: "asset-sci",
    label: "Parts SCI immobilière",
    category: "real-estate",
    envelope: "sci",
    value: 300_000,
    ifiKind: "sci",
    acquisitionDate: "2019-09-01",
    acquisitionValue: 260_000,
    isDirectlyHeld: false,
    dataQuality: {
      status: "estimated",
      supportingDocumentId: "doc-company-statutes",
      expectedAction: "Vérifier la répartition des parts et la valorisation immobilière.",
      validationStatus: "not_started",
    },
  },
  {
    id: "asset-company",
    label: "Titres de société opérationnelle",
    category: "company",
    envelope: "societe-operationnelle",
    value: 850_000,
    ifiKind: "excluded",
    isProfessionalAsset: true,
    dataQuality: {
      status: "estimated",
      supportingDocumentId: "doc-company-statutes",
      expectedAction: "Mettre à jour la dernière valorisation de la société.",
      validationStatus: "not_started",
    },
  },
];

export const demoLiabilities: Liability[] = [
  {
    id: "liability-real-estate-debt",
    label: "Dettes immobilières déclarées",
    value: 420_000,
    linkedCategory: "real-estate",
    dataQuality: {
      status: "user_declared",
      supportingDocumentId: "doc-loan-contracts",
      expectedAction: "Vérifier le capital restant dû détaillé par emprunt.",
      validationStatus: "pending",
    },
  },
];

export const demoHousehold: Household = {
  id: "household-claire-marc",
  name: "Claire et Marc",
  profile: "Foyer dirigeant patrimonial",
  members: ["Claire, 48 ans", "Marc, 51 ans"],
  children: 2,
  fiscalResidence: "France",
  professionalContext: "Dirigeants d'une PME familiale",
  assets: demoAssets,
  liabilities: demoLiabilities,
  objectives: [
    "Vérifier exposition IFI",
    "Préparer transmission aux enfants",
    "Préparer vente future de la société",
    "Produire dossier notaire / fiscaliste",
  ],
};
