import type { DemoPersona } from "@/lib/types";

export const demoPersonas: DemoPersona[] = [
  {
    id: "persona-claire-marc",
    name: "Claire et Marc",
    profile: "Dirigeants PME, IFI, SCI, transmission",
    demoObjective: "Montrer le cockpit complet, l'IFI sous seuil indicatif et les limites visibles.",
    prefilledData: ["Patrimoine 3,84 M EUR", "Dettes 420 k EUR", "SCI", "Assurance-vie", "Societe"],
    suggestedScenarios: ["IFI", "Donation avec reserve d'usufruit", "Cession partielle"],
    expectedResults: ["Base IFI 1,11 M EUR", "Completeness 72 %", "Revue professionnelle requise"],
    missingDocuments: ["Regime matrimonial", "Beneficiaires assurance-vie", "Valorisation societe"],
    sourceIds: ["src-service-public-ifi-2026", "src-legifrance-code-civil-transmission"],
    sampleReportId: "report-claire-marc-v1-1",
  },
  {
    id: "persona-couple-seuil-ifi",
    name: "Couple seuil IFI",
    profile: "Cas proche seuil avec sensibilite valorisation",
    demoObjective: "Montrer l'impact de petites variations de valeur immobiliere sur l'alerte IFI.",
    prefilledData: ["Residence principale", "Deux biens locatifs", "Dette residuelle"],
    suggestedScenarios: ["IFI", "Arbitrage immobilier"],
    expectedResults: ["Alerte de sensibilite", "Pourquoi ce resultat", "Dette a verifier"],
    missingDocuments: ["Avis de valeur", "Tableau amortissement", "Dates acquisition"],
    sourceIds: ["src-service-public-ifi-2026"],
    sampleReportId: "report-couple-seuil-ifi",
  },
  {
    id: "persona-profession-liberale",
    name: "Profession liberale",
    profile: "Revenus eleves, retraite, prevoyance",
    demoObjective: "Presenter le dossier de rendez-vous et la preparation retraite.",
    prefilledData: ["Revenus professionnels", "Immobilier", "PER", "Assurance-vie"],
    suggestedScenarios: ["Ne rien faire", "Retraite progressive", "Transmission"],
    expectedResults: ["Timeline patrimoniale", "Documents manquants", "Questions CGP"],
    missingDocuments: ["Contrat prevoyance", "PER", "Derniers avis fiscaux"],
    sourceIds: ["src-cnil-aipd", "src-legifrance-code-civil-transmission"],
    sampleReportId: "report-profession-liberale",
  },
  {
    id: "persona-entrepreneur-cession",
    name: "Entrepreneur cession",
    profile: "Liquidite apres cession, concentration entreprise",
    demoObjective: "Comparer cession partielle, reallocation et transmission avant vente.",
    prefilledData: ["Societe 2,4 M EUR", "Liquidite faible", "Projet de vente"],
    suggestedScenarios: ["Cession partielle + reallocation", "Donation avant cession"],
    expectedResults: ["Risk radar concentration", "Revue avocat fiscaliste", "Meeting brief expert-comptable"],
    missingDocuments: ["Valorisation societe", "Pacte associes", "Calendrier cession"],
    sourceIds: ["src-legifrance-code-civil-transmission", "src-cnil-aipd"],
    sampleReportId: "report-entrepreneur-cession",
  },
  {
    id: "persona-famille-recomposee",
    name: "Famille recomposee",
    profile: "Transmission, protection conjoint, assurance-vie",
    demoObjective: "Montrer les limites de couverture et la necessite de revue notaire.",
    prefilledData: ["Conjoint", "Enfants de deux unions", "Assurance-vie", "Immobilier"],
    suggestedScenarios: ["Transmission familiale", "Donation simple"],
    expectedResults: ["Checklist notaire", "Non couvert V1 sur cas complexes", "Questions ouvertes"],
    missingDocuments: ["Contrat mariage", "Clauses beneficiaires", "Donations anterieures"],
    sourceIds: ["src-legifrance-code-civil-transmission", "src-impots-donation-usufruit"],
    sampleReportId: "report-famille-recomposee",
  },
  {
    id: "persona-tpe-2026",
    name: "TPE 2026",
    profile: "Facturation electronique, e-reporting",
    demoObjective: "Tester readiness 2026/2027 pour une entreprise assujettie TVA.",
    prefilledData: ["B2B France", "Clients particuliers", "Logiciel facture", "TVA"],
    suggestedScenarios: ["Facturation electronique TPE/PME"],
    expectedResults: ["Score preparation", "Echeances 2026/2027", "Checklist actions"],
    missingDocuments: ["Plateforme agreee", "SIREN clients", "Flux internationaux"],
    sourceIds: ["src-impots-facturation-electronique-2026", "src-aife-facturation-electronique"],
    sampleReportId: "report-tpe-2026",
  },
  {
    id: "persona-non-resident-france",
    name: "Non-resident France",
    profile: "Immobilier France, perimetre IFI simple",
    demoObjective: "Montrer le bornage : non-resident simple partiel, cas complexes exclus.",
    prefilledData: ["Domicile fiscal etranger", "Immobilier France", "Dette France"],
    suggestedScenarios: ["IFI", "Arbitrage immobilier"],
    expectedResults: ["Coverage partielle", "Non residents complexes non couverts", "Revue avocat"],
    missingDocuments: ["Residence fiscale", "Conventions applicables", "Titres propriete France"],
    sourceIds: ["src-service-public-ifi-2026"],
    sampleReportId: "report-non-resident-france",
  },
];
