import type { DemoPersona } from "@/lib/types";

export const demoPersonas: DemoPersona[] = [
  {
    id: "persona-claire-marc",
    name: "Claire et Marc",
    profile: "Dirigeants PME, IFI, SCI, transmission",
    demoObjective: "Montrer le cockpit complet, l'IFI sous seuil indicatif et les limites visibles.",
    prefilledData: ["Patrimoine 3,84 M EUR", "Dettes 420 k EUR", "SCI", "Assurance-vie", "Société"],
    suggestedScenarios: ["IFI", "Donation avec réserve d'usufruit", "Cession partielle"],
    expectedResults: ["Base IFI 1,11 M EUR", "Complétude 72 %", "Revue professionnelle requise"],
    missingDocuments: ["Régime matrimonial", "Bénéficiaires assurance-vie", "Valorisation société"],
    sourceIds: ["src-service-public-ifi-2026", "src-legifrance-code-civil-transmission"],
    sampleReportId: "report-claire-marc-v1-1",
  },
  {
    id: "persona-couple-seuil-ifi",
    name: "Couple seuil IFI",
    profile: "Cas proche seuil avec sensibilite valorisation",
    demoObjective: "Montrer l'impact de petites variations de valeur immobilière sur l'alerte IFI.",
    prefilledData: ["Résidence principale", "Deux biens locatifs", "Dette résiduelle"],
    suggestedScenarios: ["IFI", "Arbitrage immobilier"],
    expectedResults: ["Alerte de sensibilite", "Pourquoi ce resultat", "Dette a verifier"],
    missingDocuments: ["Avis de valeur", "Tableau d'amortissement", "Dates d'acquisition"],
    sourceIds: ["src-service-public-ifi-2026"],
    sampleReportId: "report-couple-seuil-ifi",
  },
  {
    id: "persona-profession-liberale",
    name: "Profession libérale",
    profile: "Revenus élevés, retraite, prévoyance",
    demoObjective: "Présenter le dossier de rendez-vous et la préparation retraite.",
    prefilledData: ["Revenus professionnels", "Immobilier", "PER", "Assurance-vie"],
    suggestedScenarios: ["Ne rien faire", "Retraite progressive", "Transmission"],
    expectedResults: ["Timeline patrimoniale", "Documents manquants", "Questions CGP"],
    missingDocuments: ["Contrat prévoyance", "PER", "Derniers avis fiscaux"],
    sourceIds: ["src-cnil-aipd", "src-legifrance-code-civil-transmission"],
    sampleReportId: "report-profession-liberale",
  },
  {
    id: "persona-entrepreneur-cession",
    name: "Entrepreneur cession",
    profile: "Liquidite apres cession, concentration entreprise",
    demoObjective: "Comparer cession partielle, réallocation et transmission avant vente.",
    prefilledData: ["Société 2,4 M EUR", "Liquidité faible", "Projet de vente"],
    suggestedScenarios: ["Cession partielle + réallocation", "Donation avant cession"],
    expectedResults: ["Risk radar concentration", "Revue avocat fiscaliste", "Meeting brief expert-comptable"],
    missingDocuments: ["Valorisation société", "Pacte associés", "Calendrier cession"],
    sourceIds: ["src-legifrance-code-civil-transmission", "src-cnil-aipd"],
    sampleReportId: "report-entrepreneur-cession",
  },
  {
    id: "persona-famille-recomposee",
    name: "Famille recomposée",
    profile: "Transmission, protection conjoint, assurance-vie",
    demoObjective: "Montrer les limites de couverture et la nécessité de revue notaire.",
    prefilledData: ["Conjoint", "Enfants de deux unions", "Assurance-vie", "Immobilier"],
    suggestedScenarios: ["Transmission familiale", "Donation simple"],
    expectedResults: ["Checklist notaire", "Non couvert V2 sur cas complexes", "Questions ouvertes"],
    missingDocuments: ["Contrat mariage", "Clauses bénéficiaires", "Donations antérieures"],
    sourceIds: ["src-legifrance-code-civil-transmission", "src-impots-donation-usufruit"],
    sampleReportId: "report-famille-recomposee",
  },
  {
    id: "persona-tpe-2026",
    name: "TPE 2026",
    profile: "Facturation électronique, e-reporting",
    demoObjective: "Tester readiness 2026/2027 pour une entreprise assujettie TVA.",
    prefilledData: ["B2B France", "Clients particuliers", "Logiciel facture", "TVA"],
    suggestedScenarios: ["Facturation électronique TPE/PME"],
    expectedResults: ["Score préparation", "Échéances 2026/2027", "Checklist actions"],
    missingDocuments: ["Plateforme agréée", "SIREN clients", "Flux internationaux"],
    sourceIds: ["src-impots-facturation-electronique-2026", "src-aife-facturation-electronique"],
    sampleReportId: "report-tpe-2026",
  },
  {
    id: "persona-non-resident-france",
    name: "Non-résident France",
    profile: "Immobilier France, périmètre IFI simple",
    demoObjective: "Montrer le bornage : non-résident simple partiel, cas complexes exclus.",
    prefilledData: ["Domicile fiscal etranger", "Immobilier France", "Dette France"],
    suggestedScenarios: ["IFI", "Arbitrage immobilier"],
    expectedResults: ["Couverture partielle", "Non-résidents complexes non couverts", "Revue avocat"],
    missingDocuments: ["Résidence fiscale", "Conventions applicables", "Titres propriété France"],
    sourceIds: ["src-service-public-ifi-2026"],
    sampleReportId: "report-non-resident-france",
  },
];
