import type { EvidenceSource, SourceSnapshot } from "@/lib/types";

export const evidenceSources: EvidenceSource[] = [
  {
    id: "src-service-public-ifi-2026",
    title: "Impôt sur la fortune immobilière : calcul, décote, plafonnement et dettes",
    authority: "service-public",
    url: "https://www.service-public.gouv.fr/particuliers/vosdroits/F138",
    checkedAt: "2026-05-26",
    sourceVersion: "service-public-ifi-2026-03-06",
    verifiedAt: "2026-05-26T08:00:00.000Z",
    contentHash: "sp-ifi-2026-03-06-a91f",
    summary:
      "Seuil IFI, barème progressif, décote entre 1,3 et 1,4 M€, plafonnement, biens immobiliers et dettes déductibles sous conditions.",
    linkedRuleIds: ["rule-ifi-complete-2026-v2"],
    lastControlAt: "2026-05-26T08:15:00.000Z",
    snapshotStatus: "current",
    legalScope: "IFI",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-impots-facturation-electronique-2026",
    title: "Facturation électronique et plateformes agréées",
    authority: "impots",
    url: "https://www.impots.gouv.fr/facturation-electronique-et-plateformes-partenaires",
    checkedAt: "2026-05-26",
    sourceVersion: "impots-e-invoicing-2026-05",
    verifiedAt: "2026-05-26T08:05:00.000Z",
    contentHash: "impots-fe-2026-05-b12c",
    summary:
      "Calendrier reception 2026, emission 2026/2027, plateformes agreees et obligations e-reporting.",
    linkedRuleIds: ["rule-e-invoicing-readiness-2026-v1"],
    lastControlAt: "2026-05-26T08:16:00.000Z",
    snapshotStatus: "current",
    legalScope: "facturation-electronique",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-cnil-aipd",
    title: "Réaliser une analyse d'impact relative à la protection des données",
    authority: "cnil",
    url: "https://www.cnil.fr/fr/realiser-une-analyse-dimpact-si-necessaire",
    legalReference: "RGPD - analyse d'impact relative à la protection des données",
    archivedSnapshotLabel: "snapshot-offline-cnil-aipd-2026-05-27",
    checkedAt: "2026-05-26",
    sourceVersion: "cnil-aipd-2026-05",
    verifiedAt: "2026-05-26T08:10:00.000Z",
    contentHash: "cnil-aipd-2026-05-c33d",
    summary:
      "Cadre AIPD pour traitements susceptibles d'engendrer un risque élevé, avec mesures de réduction et documentation.",
    linkedRuleIds: ["rule-rgpd-dpia-demo-2026-v1", "rule-ai-governance-2026-v1"],
    lastControlAt: "2026-05-26T08:17:00.000Z",
    snapshotStatus: "current",
    legalScope: "rgpd",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-cnil-registre-traitements",
    title: "CNIL : registre des activités de traitement",
    authority: "cnil",
    url: "https://www.cnil.fr/fr/RGPD-le-registre-des-activites-de-traitement",
    legalReference: "RGPD - article 30",
    archivedSnapshotLabel: "snapshot-offline-cnil-registre-rgpd-art-30-2026-05-27",
    checkedAt: "2026-05-27",
    sourceVersion: "cnil-registre-rgpd-art-30-2026-05",
    verifiedAt: "2026-05-27T08:12:00.000Z",
    contentHash: "cnil-registre-rgpd-art-30-2026",
    summary:
      "Référentiel CNIL pour tenir un registre des activités de traitement : finalités, catégories de données, destinataires, durées et mesures de sécurité.",
    linkedRuleIds: ["rule-rgpd-dpia-demo-2026-v1"],
    lastControlAt: "2026-05-27T08:18:00.000Z",
    snapshotStatus: "current",
    legalScope: "rgpd",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-code-civil-transmission",
    title: "Code civil : succession, réserve et libéralités",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/id/LEGITEXT000006070721/",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-code-civil-2026-05",
    verifiedAt: "2026-05-26T08:20:00.000Z",
    contentHash: "legifrance-civil-2026-05-d44e",
    summary:
      "Références civiles pour succession, réserve héréditaire, libéralités et points de validation notaire.",
    linkedRuleIds: [
      "rule-transmission-checklist-2026-v1",
      "rule-donation-usufruit-2026-v1",
      "rule-sci-arbitrage-2026-v1",
    ],
    lastControlAt: "2026-05-26T08:30:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "transmission",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-bofip-plus-value-immobiliere",
    title: "BOFiP : plus-values immobilières des particuliers",
    authority: "bofip",
    url: "https://bofip.impots.gouv.fr/bofip/265-PGP.html",
    checkedAt: "2026-05-26",
    sourceVersion: "bofip-plus-value-2026-05",
    verifiedAt: "2026-05-26T08:25:00.000Z",
    contentHash: "bofip-pvi-2026-05-e55f",
    summary:
      "Structure de référence pour plus-value immobilière, durée de détention, abattements et cas particuliers.",
    linkedRuleIds: ["rule-plus-value-immobiliere-2026-v1"],
    lastControlAt: "2026-05-26T08:31:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "plus-value",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-impots-donation-usufruit",
    title: "impots.gouv.fr : barème fiscal usufruit et nue-propriété",
    authority: "impots",
    url: "https://www.impots.gouv.fr/particulier/questions/comment-sont-evalues-lusufruit-et-la-nue-propriete",
    checkedAt: "2026-05-26",
    sourceVersion: "impots-usufruit-2026-05",
    verifiedAt: "2026-05-26T08:26:00.000Z",
    contentHash: "impots-usufruit-2026-05-f66a",
    summary:
      "Barème indicatif usufruit/nue-propriété à valider dans le contexte de donation et transmission.",
    linkedRuleIds: ["rule-donation-usufruit-2026-v1"],
    lastControlAt: "2026-05-26T08:32:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "donation",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-aife-facturation-electronique",
    title: "AIFE : programme facturation électronique",
    authority: "aife",
    url: "https://www.economie.gouv.fr/aife/facturation-electronique",
    checkedAt: "2026-05-26",
    sourceVersion: "aife-fe-2026-05",
    verifiedAt: "2026-05-26T08:28:00.000Z",
    contentHash: "aife-fe-2026-05-g77b",
    summary:
      "Programme facturation électronique, formats et préparation opérationnelle des entreprises.",
    linkedRuleIds: ["rule-e-invoicing-readiness-2026-v1"],
    lastControlAt: "2026-05-26T08:33:00.000Z",
    snapshotStatus: "current",
    legalScope: "facturation-electronique",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-eu-ai-act-transparency",
    title: "Commission européenne : cadre réglementaire sur l'IA",
    authority: "commission-europeenne",
    url: "https://digital-strategy.ec.europa.eu/fr/policies/regulatory-framework-ai",
    checkedAt: "2026-05-26",
    sourceVersion: "eu-ai-act-2026-05",
    verifiedAt: "2026-05-26T08:35:00.000Z",
    contentHash: "eu-ai-act-2026-05-h88c",
    summary:
      "Cadre de gouvernance IA utilise comme reference de prudence, sans IA runtime activee en V1.1.",
    linkedRuleIds: ["rule-ai-governance-2026-v1"],
    lastControlAt: "2026-05-26T08:40:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "ai-act",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-service-public-pfu-2026",
    title: "Entreprendre Service-Public : PFU 31,4 % au 1er janvier 2026",
    authority: "service-public",
    url: "https://entreprendre.service-public.gouv.fr/actualites/A18796",
    legalReference: "Code de la sécurité sociale - Article L136-8",
    archivedSnapshotLabel: "snapshot-offline-service-public-pfu-a18796-2026-05-27",
    checkedAt: "2026-05-27",
    sourceVersion: "entreprendre-service-public-pfu-a18796-2026-02-10",
    verifiedAt: "2026-05-27T09:05:00.000Z",
    contentHash: "sp-entreprendre-pfu-a18796-2026-31-4",
    summary:
      "Actualité officielle : PFU porté de 30 % à 31,4 % au 1er janvier 2026, avec 12,8 % d'impôt sur le revenu et 18,6 % de prélèvements sociaux.",
    linkedRuleIds: ["rule-ir-pfu-cdhr-2026-v2"],
    lastControlAt: "2026-05-27T09:15:00.000Z",
    snapshotStatus: "current",
    legalScope: "ir-pfu-cdhr",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-economie-cdhr-2026",
    title: "Contribution différentielle sur les hauts revenus",
    authority: "impots",
    url: "https://presse.economie.gouv.fr/mise-en-place-et-paiement-de-la-contribution-differentielle-sur-les-hauts-revenus-cdhr/",
    checkedAt: "2026-05-26",
    sourceVersion: "economie-cdhr-2025-11-14",
    verifiedAt: "2026-05-26T09:10:00.000Z",
    contentHash: "economie-cdhr-2026-k22l",
    summary:
      "Contribution assurant une imposition minimale de 20 % pour les foyers dépassant 250 k€ ou 500 k€ de revenu fiscal de référence.",
    linkedRuleIds: ["rule-ir-pfu-cdhr-2026-v2"],
    lastControlAt: "2026-05-26T09:16:00.000Z",
    snapshotStatus: "current",
    legalScope: "ir-pfu-cdhr",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-dutreil-2026",
    title: "LF 2026 art. 8 : Pacte Dutreil",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000053508196",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-lf-2026-art-8",
    verifiedAt: "2026-05-26T09:20:00.000Z",
    contentHash: "legifrance-dutreil-2026-m44n",
    summary:
      "Exonération de 75 %, exclusions d'actifs non affectés et engagements à valider pour transmission d'entreprise.",
    linkedRuleIds: ["rule-dutreil-2026-v2"],
    lastControlAt: "2026-05-26T09:25:00.000Z",
    snapshotStatus: "current",
    legalScope: "dutreil",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-apport-cession-2026",
    title: "LF 2026 art. 11 : apport-cession 150-0 B ter",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000053508205",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-lf-2026-art-11",
    verifiedAt: "2026-05-26T09:30:00.000Z",
    contentHash: "legifrance-apport-cession-2026-p55q",
    summary:
      "Réinvestissement porté à 70 %, délai de trois ans et conservation à documenter pour report d'imposition.",
    linkedRuleIds: ["rule-apport-cession-2026-v2"],
    lastControlAt: "2026-05-26T09:35:00.000Z",
    snapshotStatus: "current",
    legalScope: "apport-cession",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-holding-tax-2026",
    title: "LF 2026 art. 7 : taxe holding patrimoniale",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/eli/loi/2026/2/19/2026-103/jo/article_7",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-lf-2026-art-7",
    verifiedAt: "2026-05-26T09:40:00.000Z",
    contentHash: "legifrance-holding-tax-2026-r66s",
    summary:
      "Taxe sur actifs non professionnels détenus par certaines holdings patrimoniales, conditions cumulatives et taux de 20 %.",
    linkedRuleIds: ["rule-holding-tax-2026-v2"],
    lastControlAt: "2026-05-26T09:45:00.000Z",
    snapshotStatus: "current",
    legalScope: "holding-tax",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-amf-mif2-adequation",
    title: "AMF : exigences d'adéquation MIF II",
    authority: "amf",
    url: "https://www.amf-france.org/fr/espace-professionnels/obligations-des-professionnels/obligations-mif-2",
    checkedAt: "2026-05-26",
    sourceVersion: "amf-mif2-2026-05",
    verifiedAt: "2026-05-26T09:50:00.000Z",
    contentHash: "amf-mif2-documents-2026-t77u",
    summary:
      "Référentiel documentaire pour rapport d'adéquation, connaissance client et conservation des éléments de conseil.",
    linkedRuleIds: ["rule-documents-cabinet-2026-v2"],
    lastControlAt: "2026-05-26T09:55:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "mif2-dda",
    reliability: "official",
    status: "to-review",
  },
];

export const sourceSnapshots: SourceSnapshot[] = evidenceSources.map((source) => ({
  id: `snapshot-${source.id}`,
  sourceId: source.id,
  sourceVersion: source.sourceVersion,
  capturedAt: source.verifiedAt,
  contentHash: source.contentHash,
  summary: source.summary,
  linkedRuleIds: source.linkedRuleIds,
  status: source.snapshotStatus,
}));

export function getEvidenceSource(id: string) {
  return evidenceSources.find((source) => source.id === id);
}

export function getSourceSnapshot(sourceId: string) {
  return sourceSnapshots.find((snapshot) => snapshot.sourceId === sourceId);
}
