import type { EvidenceSource, SourceSnapshot } from "@/lib/types";

export const evidenceSources: EvidenceSource[] = [
  {
    id: "src-service-public-ifi-2026",
    title: "Impôt sur la fortune immobilière : calcul, décote, plafonnement et dettes",
    authority: "service-public",
    url: "https://www.service-public.gouv.fr/particuliers/vosdroits/F138",
    checkedAt: "2026-05-26",
    sourceVersion: "service-public-ifi-2026-03-06",
    verifiedAt: "2026-05-26T08:00:00.000Z",
    contentHash: "sp-ifi-2026-03-06-a91f",
    summary:
      "Seuil IFI, barème progressif, décote entre 1,3 et 1,4 M€, plafonnement, biens immobiliers et dettes déductibles sous conditions.",
    linkedRuleIds: ["rule-ifi-complete-2026-v2"],
    lastControlAt: "2026-05-26T08:15:00.000Z",
    snapshotStatus: "current",
    legalScope: "IFI",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-impots-facturation-electronique-2026",
    title: "Facturation électronique et plateformes agréées",
    authority: "impots",
    url: "https://www.impots.gouv.fr/facturation-electronique-et-plateformes-partenaires",
    checkedAt: "2026-05-26",
    sourceVersion: "impots-e-invoicing-2026-05",
    verifiedAt: "2026-05-26T08:05:00.000Z",
    contentHash: "impots-fe-2026-05-b12c",
    summary:
      "Calendrier reception 2026, emission 2026/2027, plateformes agreees et obligations e-reporting.",
    linkedRuleIds: ["rule-e-invoicing-readiness-2026-v1"],
    lastControlAt: "2026-05-26T08:16:00.000Z",
    snapshotStatus: "current",
    legalScope: "facturation-electronique",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-cnil-aipd",
    title: "Réaliser une analyse d'impact relative à la protection des données",
    authority: "cnil",
    url: "https://www.cnil.fr/fr/realiser-une-analyse-dimpact-si-necessaire",
    legalReference: "RGPD - analyse d'impact relative à la protection des données",
    archivedSnapshotLabel: "snapshot-offline-cnil-aipd-2026-05-27",
    checkedAt: "2026-05-26",
    sourceVersion: "cnil-aipd-2026-05",
    verifiedAt: "2026-05-26T08:10:00.000Z",
    contentHash: "cnil-aipd-2026-05-c33d",
    summary:
      "Cadre AIPD pour traitements susceptibles d'engendrer un risque élevé, avec mesures de réduction et documentation.",
    linkedRuleIds: ["rule-rgpd-dpia-demo-2026-v1", "rule-ai-governance-2026-v1"],
    lastControlAt: "2026-05-26T08:17:00.000Z",
    snapshotStatus: "current",
    legalScope: "rgpd",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-cnil-registre-traitements",
    title: "CNIL : registre des activités de traitement",
    authority: "cnil",
    url: "https://www.cnil.fr/fr/RGPD-le-registre-des-activites-de-traitement",
    legalReference: "RGPD - article 30",
    archivedSnapshotLabel: "snapshot-offline-cnil-registre-rgpd-art-30-2026-05-27",
    checkedAt: "2026-05-27",
    sourceVersion: "cnil-registre-rgpd-art-30-2026-05",
    verifiedAt: "2026-05-27T08:12:00.000Z",
    contentHash: "cnil-registre-rgpd-art-30-2026",
    summary:
      "Référentiel CNIL pour tenir un registre des activités de traitement : finalités, catégories de données, destinataires, durées et mesures de sécurité.",
    linkedRuleIds: ["rule-rgpd-dpia-demo-2026-v1"],
    lastControlAt: "2026-05-27T08:18:00.000Z",
    snapshotStatus: "current",
    legalScope: "rgpd",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-code-civil-transmission",
    title: "Code civil : succession, réserve et libéralités",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/codes/id/LEGITEXT000006070721/",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-code-civil-2026-05",
    verifiedAt: "2026-05-26T08:20:00.000Z",
    contentHash: "legifrance-civil-2026-05-d44e",
    summary:
      "Références civiles pour succession, réserve héréditaire, libéralités et points de validation notaire.",
    linkedRuleIds: [
      "rule-transmission-checklist-2026-v1",
      "rule-donation-usufruit-2026-v1",
      "rule-sci-arbitrage-2026-v1",
    ],
    lastControlAt: "2026-05-26T08:30:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "transmission",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-bofip-plus-value-immobiliere",
    title: "BOFiP : plus-values immobilières des particuliers",
    authority: "bofip",
    url: "https://bofip.impots.gouv.fr/bofip/265-PGP.html",
    checkedAt: "2026-05-26",
    sourceVersion: "bofip-plus-value-2026-05",
    verifiedAt: "2026-05-26T08:25:00.000Z",
    contentHash: "bofip-pvi-2026-05-e55f",
    summary:
      "Structure de référence pour plus-value immobilière, durée de détention, abattements et cas particuliers.",
    linkedRuleIds: ["rule-plus-value-immobiliere-2026-v1"],
    lastControlAt: "2026-05-26T08:31:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "plus-value",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-impots-donation-usufruit",
    title: "impots.gouv.fr : barème fiscal usufruit et nue-propriété",
    authority: "impots",
    url: "https://www.impots.gouv.fr/particulier/questions/comment-sont-evalues-lusufruit-et-la-nue-propriete",
    checkedAt: "2026-05-26",
    sourceVersion: "impots-usufruit-2026-05",
    verifiedAt: "2026-05-26T08:26:00.000Z",
    contentHash: "impots-usufruit-2026-05-f66a",
    summary:
      "Barème indicatif usufruit/nue-propriété à valider dans le contexte de donation et transmission.",
    linkedRuleIds: ["rule-donation-usufruit-2026-v1"],
    lastControlAt: "2026-05-26T08:32:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "donation",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-aife-facturation-electronique",
    title: "AIFE : programme facturation électronique",
    authority: "aife",
    url: "https://www.economie.gouv.fr/aife/facturation-electronique",
    checkedAt: "2026-05-26",
    sourceVersion: "aife-fe-2026-05",
    verifiedAt: "2026-05-26T08:28:00.000Z",
    contentHash: "aife-fe-2026-05-g77b",
    summary:
      "Programme facturation électronique, formats et préparation opérationnelle des entreprises.",
    linkedRuleIds: ["rule-e-invoicing-readiness-2026-v1"],
    lastControlAt: "2026-05-26T08:33:00.000Z",
    snapshotStatus: "current",
    legalScope: "facturation-electronique",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-eu-ai-act-transparency",
    title: "Commission européenne : cadre réglementaire sur l'IA",
    authority: "commission-europeenne",
    url: "https://digital-strategy.ec.europa.eu/fr/policies/regulatory-framework-ai",
    checkedAt: "2026-05-26",
    sourceVersion: "eu-ai-act-2026-05",
    verifiedAt: "2026-05-26T08:35:00.000Z",
    contentHash: "eu-ai-act-2026-05-h88c",
    summary:
      "Cadre de gouvernance IA utilise comme reference de prudence, sans IA runtime activee en V1.1.",
    linkedRuleIds: ["rule-ai-governance-2026-v1"],
    lastControlAt: "2026-05-26T08:40:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "ai-act",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-service-public-pfu-2026",
    title: "Entreprendre Service-Public : PFU 31,4 % au 1er janvier 2026",
    authority: "service-public",
    url: "https://entreprendre.service-public.gouv.fr/actualites/A18796",
    legalReference: "Code de la sécurité sociale - Article L136-8",
    archivedSnapshotLabel: "snapshot-offline-service-public-pfu-a18796-2026-05-27",
    checkedAt: "2026-05-27",
    sourceVersion: "entreprendre-service-public-pfu-a18796-2026-02-10",
    verifiedAt: "2026-05-27T09:05:00.000Z",
    contentHash: "sp-entreprendre-pfu-a18796-2026-31-4",
    summary:
      "Actualité officielle : PFU porté de 30 % à 31,4 % au 1er janvier 2026, avec 12,8 % d'impôt sur le revenu et 18,6 % de prélèvements sociaux.",
    linkedRuleIds: ["rule-ir-pfu-cdhr-2026-v2"],
    lastControlAt: "2026-05-27T09:15:00.000Z",
    snapshotStatus: "current",
    legalScope: "ir-pfu-cdhr",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-economie-cdhr-2026",
    title: "Contribution différentielle sur les hauts revenus",
    authority: "impots",
    url: "https://presse.economie.gouv.fr/mise-en-place-et-paiement-de-la-contribution-differentielle-sur-les-hauts-revenus-cdhr/",
    checkedAt: "2026-05-26",
    sourceVersion: "economie-cdhr-2025-11-14",
    verifiedAt: "2026-05-26T09:10:00.000Z",
    contentHash: "economie-cdhr-2026-k22l",
    summary:
      "Contribution assurant une imposition minimale de 20 % pour les foyers dépassant 250 k€ ou 500 k€ de revenu fiscal de référence.",
    linkedRuleIds: ["rule-ir-pfu-cdhr-2026-v2"],
    lastControlAt: "2026-05-26T09:16:00.000Z",
    snapshotStatus: "current",
    legalScope: "ir-pfu-cdhr",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-dutreil-2026",
    title: "LF 2026 art. 8 : Pacte Dutreil",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000053508196",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-lf-2026-art-8",
    verifiedAt: "2026-05-26T09:20:00.000Z",
    contentHash: "legifrance-dutreil-2026-m44n",
    summary:
      "Exonération de 75 %, exclusions d'actifs non affectés et engagements à valider pour transmission d'entreprise.",
    linkedRuleIds: ["rule-dutreil-2026-v2"],
    lastControlAt: "2026-05-26T09:25:00.000Z",
    snapshotStatus: "current",
    legalScope: "dutreil",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-apport-cession-2026",
    title: "LF 2026 art. 11 : apport-cession 150-0 B ter",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000053508205",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-lf-2026-art-11",
    verifiedAt: "2026-05-26T09:30:00.000Z",
    contentHash: "legifrance-apport-cession-2026-p55q",
    summary:
      "Réinvestissement porté à 70 %, délai de trois ans et conservation à documenter pour report d'imposition.",
    linkedRuleIds: ["rule-apport-cession-2026-v2"],
    lastControlAt: "2026-05-26T09:35:00.000Z",
    snapshotStatus: "current",
    legalScope: "apport-cession",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-legifrance-holding-tax-2026",
    title: "LF 2026 art. 7 : taxe holding patrimoniale",
    authority: "legifrance",
    url: "https://www.legifrance.gouv.fr/eli/loi/2026/2/19/2026-103/jo/article_7",
    checkedAt: "2026-05-26",
    sourceVersion: "legifrance-lf-2026-art-7",
    verifiedAt: "2026-05-26T09:40:00.000Z",
    contentHash: "legifrance-holding-tax-2026-r66s",
    summary:
      "Taxe sur actifs non professionnels détenus par certaines holdings patrimoniales, conditions cumulatives et taux de 20 %.",
    linkedRuleIds: ["rule-holding-tax-2026-v2"],
    lastControlAt: "2026-05-26T09:45:00.000Z",
    snapshotStatus: "current",
    legalScope: "holding-tax",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-amf-mif2-adequation",
    title: "AMF : exigences d'adéquation MIF II",
    authority: "amf",
    url: "https://www.amf-france.org/fr/espace-professionnels/obligations-des-professionnels/obligations-mif-2",
    checkedAt: "2026-05-26",
    sourceVersion: "amf-mif2-2026-05",
    verifiedAt: "2026-05-26T09:50:00.000Z",
    contentHash: "amf-mif2-documents-2026-t77u",
    summary:
      "Référentiel documentaire pour rapport d'adéquation, connaissance client et conservation des éléments de conseil.",
    linkedRuleIds: ["rule-documents-cabinet-2026-v2"],
    lastControlAt: "2026-05-26T09:55:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "mif2-dda",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-service-public-pea-2026",
    title: "Service-Public : Plan d'épargne en actions",
    authority: "service-public",
    url: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2385",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-pea-2026-05-22",
    verifiedAt: "2026-06-04T08:00:00.000Z",
    contentHash: "service-public-pea-2026-05-22-v23",
    summary:
      "Règles PEA : plafond, conditions d'ouverture, retraits après cinq ans, exonération d'impôt sur le revenu et prélèvements sociaux à contrôler.",
    linkedRuleIds: ["rule-pea-withdrawal-2026-v1"],
    lastControlAt: "2026-06-04T08:10:00.000Z",
    snapshotStatus: "current",
    legalScope: "pea",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-service-public-per-deduction-2026",
    title: "Service-Public : cotisations d'épargne retraite et déduction",
    authority: "service-public",
    url: "https://www.service-public.gouv.fr/particuliers/vosdroits/F14709",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-per-deduction-2026-06",
    verifiedAt: "2026-06-04T08:02:00.000Z",
    contentHash: "service-public-per-deduction-2026-v23",
    summary:
      "Plafonds de déduction PER, reliquats non utilisés, déclaration des cotisations et règles particulières à vérifier.",
    linkedRuleIds: ["rule-per-deduction-2026-v1"],
    lastControlAt: "2026-06-04T08:12:00.000Z",
    snapshotStatus: "current",
    legalScope: "per",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-impots-epargne-retraite-2026",
    title: "impots.gouv.fr : épargne retraite et plafonds disponibles",
    authority: "impots",
    url: "https://www.impots.gouv.fr/particulier/epargne-retraite",
    checkedAt: "2026-06-04",
    sourceVersion: "impots-epargne-retraite-2026-06",
    verifiedAt: "2026-06-04T08:04:00.000Z",
    contentHash: "impots-epargne-retraite-2026-v23",
    summary:
      "Limites de déduction, plafonds disponibles par membre du foyer et information issue de l'avis d'impôt.",
    linkedRuleIds: ["rule-per-deduction-2026-v1"],
    lastControlAt: "2026-06-04T08:14:00.000Z",
    snapshotStatus: "current",
    legalScope: "per",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-service-public-don-familial-2026",
    title: "Service-Public : don familial d'une somme d'argent",
    authority: "service-public",
    url: "https://www.service-public.gouv.fr/particuliers/vosdroits/F36656",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-don-familial-2026-06",
    verifiedAt: "2026-06-04T08:06:00.000Z",
    contentHash: "service-public-don-familial-2026-v23",
    summary:
      "Conditions déclaratives et familiales utiles à la revue des donations et présents d'usage.",
    linkedRuleIds: ["rule-transmission-checklist-2026-v1"],
    lastControlAt: "2026-06-04T08:16:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "donation",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-amf-durabilite-2022",
    title: "AMF : préférences de durabilité dans le conseil financier",
    authority: "amf",
    url: "https://www.amf-france.org/fr/espace-epargnants/actualites-mises-en-garde/vos-preferences-en-matiere-de-developpement-durable-ce-qui-change-pour-vos-placements",
    checkedAt: "2026-06-04",
    sourceVersion: "amf-durabilite-2022-07-26",
    verifiedAt: "2026-06-04T08:08:00.000Z",
    contentHash: "amf-durabilite-2022-v23",
    summary:
      "Depuis août 2022, le conseil financier doit intégrer les préférences de durabilité dans la connaissance client.",
    linkedRuleIds: ["rule-documents-cabinet-2026-v2"],
    lastControlAt: "2026-06-04T08:18:00.000Z",
    snapshotStatus: "current",
    legalScope: "mif2-dda",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-eurlex-sca-2018-389",
    title: "EUR-Lex : authentification forte et communication sécurisée",
    authority: "eurlex",
    url: "https://eur-lex.europa.eu/eli/reg_del/2018/389/oj",
    checkedAt: "2026-06-04",
    sourceVersion: "eurlex-reg-del-2018-389",
    verifiedAt: "2026-06-04T08:20:00.000Z",
    contentHash: "eurlex-sca-2018-389-v23",
    summary:
      "Cadre européen d'authentification forte et de standards sécurisés pour les accès de paiement.",
    linkedRuleIds: ["rule-bank-import-demo-2026-v1"],
    lastControlAt: "2026-06-04T08:24:00.000Z",
    snapshotStatus: "current",
    legalScope: "open-banking",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-banque-france-sca-2022",
    title: "Banque de France : sécurité des moyens de paiement",
    authority: "banque-france",
    url: "https://www.banque-france.fr/system/files/2023-09/rapport_annuel_de_lobservatoire_de_la_securite_des_moyens_de_paiement_2022.pdf",
    checkedAt: "2026-06-04",
    sourceVersion: "banque-france-osmp-2022",
    verifiedAt: "2026-06-04T08:22:00.000Z",
    contentHash: "banque-france-osmp-2022-v23",
    summary:
      "Rapport institutionnel utilisé pour cadrer la réduction de fraude et l'authentification forte dans l'import simulé.",
    linkedRuleIds: ["rule-bank-import-demo-2026-v1"],
    lastControlAt: "2026-06-04T08:26:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "open-banking",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-eurlex-dac6-2018-822",
    title: "EUR-Lex : DAC6 et dispositifs transfrontières",
    authority: "eurlex",
    url: "https://eur-lex.europa.eu/eli/dir/2018/822/oj",
    checkedAt: "2026-06-04",
    sourceVersion: "eurlex-dir-2018-822",
    verifiedAt: "2026-06-04T08:28:00.000Z",
    contentHash: "eurlex-dac6-2018-822-v23",
    summary:
      "Cadre de transparence fiscale pour dispositifs transfrontières, utilisé comme signal de revue renforcée.",
    linkedRuleIds: ["rule-manual-review-complexity-2026-v1"],
    lastControlAt: "2026-06-04T08:32:00.000Z",
    snapshotStatus: "current",
    legalScope: "dac6-dac7",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-eurlex-dac7-2021-514",
    title: "EUR-Lex : DAC7 et coopération administrative fiscale",
    authority: "eurlex",
    url: "https://eur-lex.europa.eu/eli/dir/2021/514/oj",
    checkedAt: "2026-06-04",
    sourceVersion: "eurlex-dir-2021-514",
    verifiedAt: "2026-06-04T08:30:00.000Z",
    contentHash: "eurlex-dac7-2021-514-v23",
    summary:
      "Cadre européen de coopération administrative en matière fiscale, utile pour signaux de transparence et plateformes.",
    linkedRuleIds: ["rule-manual-review-complexity-2026-v1"],
    lastControlAt: "2026-06-04T08:34:00.000Z",
    snapshotStatus: "current",
    legalScope: "dac6-dac7",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-eurlex-aml-2015-849",
    title: "EUR-Lex : prévention du blanchiment et bénéficiaire effectif",
    authority: "eurlex",
    url: "https://eur-lex.europa.eu/legal-content/fr/TXT/?uri=CELEX%3A32015L0849",
    checkedAt: "2026-06-04",
    sourceVersion: "eurlex-dir-2015-849",
    verifiedAt: "2026-06-04T08:36:00.000Z",
    contentHash: "eurlex-aml-2015-849-v23",
    summary:
      "Cadre LCB-FT utilisé pour bénéficiaire effectif, origine des fonds et vigilance renforcée.",
    linkedRuleIds: ["rule-manual-review-complexity-2026-v1", "rule-bank-import-demo-2026-v1"],
    lastControlAt: "2026-06-04T08:40:00.000Z",
    snapshotStatus: "current",
    legalScope: "lcb-ft",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-service-public-succession-declaration-2025",
    title: "Service-Public : declaration de succession",
    authority: "service-public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F80",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-succession-f80-2025-01-29",
    verifiedAt: "2026-06-04T09:00:00.000Z",
    contentHash: "service-public-succession-f80-v24",
    summary:
      "Declaration de succession, seuils de dispense, intervention du notaire et paiement des droits selon la situation du foyer.",
    linkedRuleIds: ["rule-succession-checklist-2026-v1", "rule-succession-liquidity-stress-2026-v1"],
    lastControlAt: "2026-06-04T09:10:00.000Z",
    snapshotStatus: "current",
    legalScope: "succession",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-service-public-succession-rights-2024",
    title: "Service-Public : droits de succession selon le lien familial",
    authority: "service-public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F35794",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-succession-droits-2024",
    verifiedAt: "2026-06-04T09:02:00.000Z",
    contentHash: "service-public-succession-rights-v24",
    summary:
      "Cadre officiel pour rappeler que les droits de succession varient selon la parente et doivent etre liquides par dossier.",
    linkedRuleIds: ["rule-succession-checklist-2026-v1", "rule-succession-liquidity-stress-2026-v1"],
    lastControlAt: "2026-06-04T09:12:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "succession",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-service-public-rapport-fiscal-succession-2025",
    title: "Service-Public : rappel fiscal des donations dans une succession",
    authority: "service-public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F32272",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-rapport-fiscal-succession-2025-06-23",
    verifiedAt: "2026-06-04T09:04:00.000Z",
    contentHash: "service-public-rapport-fiscal-succession-v24",
    summary:
      "Rappel des donations anterieures et effet sur la liquidation : la demo signale la question sans conclure seule.",
    linkedRuleIds: ["rule-succession-checklist-2026-v1"],
    lastControlAt: "2026-06-04T09:14:00.000Z",
    snapshotStatus: "current",
    legalScope: "succession",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-service-public-indivision-2025",
    title: "Service-Public : indivision",
    authority: "service-public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F1296",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-indivision-2025",
    verifiedAt: "2026-06-04T09:06:00.000Z",
    contentHash: "service-public-indivision-v24",
    summary:
      "Reference de vulgarisation pour quote-parts, decisions et vigilance sur la detention collective.",
    linkedRuleIds: ["rule-succession-checklist-2026-v1"],
    lastControlAt: "2026-06-04T09:16:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "succession",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-service-public-per-release-2025",
    title: "Service-Public : PER individuel et sortie anticipee residence principale",
    authority: "service-public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F36526/0",
    checkedAt: "2026-06-04",
    sourceVersion: "service-public-per-f36526-2025",
    verifiedAt: "2026-06-04T09:08:00.000Z",
    contentHash: "service-public-per-release-v24",
    summary:
      "Deblocage anticipe du PER pour acquisition de residence principale, avec fiscalite a distinguer selon versements et gains.",
    linkedRuleIds: ["rule-per-early-exit-primary-home-2026-v1"],
    lastControlAt: "2026-06-04T09:18:00.000Z",
    snapshotStatus: "current",
    legalScope: "per",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-bofip-per-fiscal-regime-2026",
    title: "BOFiP : regime d'imposition des plans d'epargne retraite",
    authority: "bofip",
    url: "https://bofip.impots.gouv.fr/doctrine/pgp/14911-PGP",
    checkedAt: "2026-06-04",
    sourceVersion: "bofip-per-regime-2026",
    verifiedAt: "2026-06-04T09:09:00.000Z",
    contentHash: "bofip-per-regime-v24",
    summary:
      "Tableaux de traitement fiscal et social des sorties de PER, utilises comme source de revue pour versements et produits.",
    linkedRuleIds: ["rule-per-early-exit-primary-home-2026-v1"],
    lastControlAt: "2026-06-04T09:19:00.000Z",
    snapshotStatus: "current",
    legalScope: "per",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-amf-cif-orias-2026",
    title: "AMF : conseillers en investissements financiers",
    authority: "amf",
    url: "https://www.amf-france.org/fr/espace-professionnels/autres-profils/conseillers-en-investissements-financiers-cif",
    checkedAt: "2026-06-04",
    sourceVersion: "amf-cif-orias-2026",
    verifiedAt: "2026-06-04T09:20:00.000Z",
    contentHash: "amf-cif-orias-v24",
    summary:
      "Cadre CIF utilise pour distinguer information, simulation et conseil personnalise soumis a obligations professionnelles.",
    linkedRuleIds: ["rule-product-adequacy-demo-2026-v1", "rule-regulatory-controls-2026-v1"],
    lastControlAt: "2026-06-04T09:28:00.000Z",
    snapshotStatus: "current",
    legalScope: "cif-orias",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-amf-lcb-ft-2021",
    title: "AMF : lutte anti-blanchiment et financement du terrorisme",
    authority: "amf",
    url: "https://www.amf-france.org/fr/actualites-publications/dossiers-thematiques/lutte-anti-blanchiment",
    checkedAt: "2026-06-04",
    sourceVersion: "amf-lcb-ft-2021-2026-control",
    verifiedAt: "2026-06-04T09:22:00.000Z",
    contentHash: "amf-lcb-ft-v24",
    summary:
      "Dossier AMF sur les obligations de vigilance, origine des fonds et escalade des risques LCB-FT.",
    linkedRuleIds: ["rule-regulatory-controls-2026-v1", "rule-manual-review-complexity-2026-v1"],
    lastControlAt: "2026-06-04T09:30:00.000Z",
    snapshotStatus: "current",
    legalScope: "lcb-ft",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-cnil-rgpd-privacy-by-design",
    title: "CNIL : RGPD, responsabilite et protection des donnees des la conception",
    authority: "cnil",
    url: "https://cnil.fr/fr/comprendre-le-rgpd/reglement-general-sur-la-protection-des-donnees-ce-qui-change-pour-les-professionnels",
    checkedAt: "2026-06-04",
    sourceVersion: "cnil-rgpd-privacy-by-design-2026",
    verifiedAt: "2026-06-04T09:24:00.000Z",
    contentHash: "cnil-rgpd-privacy-design-v24",
    summary:
      "Reference CNIL pour accountability, minimisation et prise en compte de la protection des donnees dans le produit.",
    linkedRuleIds: ["rule-regulatory-controls-2026-v1"],
    lastControlAt: "2026-06-04T09:32:00.000Z",
    snapshotStatus: "current",
    legalScope: "rgpd",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-cnil-profiling-automated-decision",
    title: "CNIL : profilage et decision entierement automatisee",
    authority: "cnil",
    url: "https://www.cnil.fr/fr/profilage-et-decision-entierement-automatisee",
    checkedAt: "2026-06-04",
    sourceVersion: "cnil-profilage-decision-auto-2026",
    verifiedAt: "2026-06-04T09:26:00.000Z",
    contentHash: "cnil-profiling-decision-v24",
    summary:
      "Garde-fou contre les conclusions automatiques : profilage et decisions automatisees doivent etre encadres.",
    linkedRuleIds: ["rule-product-adequacy-demo-2026-v1", "rule-regulatory-controls-2026-v1"],
    lastControlAt: "2026-06-04T09:34:00.000Z",
    snapshotStatus: "current",
    legalScope: "rgpd",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-acpr-dora-2026",
    title: "ACPR : Digital Operational Resilience Act (DORA)",
    authority: "acpr",
    url: "https://acpr.banque-france.fr/controler/publications-du-controle/digital-operational-resilience-act-dora",
    checkedAt: "2026-06-04",
    sourceVersion: "acpr-dora-2026",
    verifiedAt: "2026-06-04T09:36:00.000Z",
    contentHash: "acpr-dora-v24",
    summary:
      "Cadre de resilience operationnelle numerique retenu comme jalon hors MVP pour connecteurs et exploitation reelle.",
    linkedRuleIds: ["rule-regulatory-controls-2026-v1"],
    lastControlAt: "2026-06-04T09:42:00.000Z",
    snapshotStatus: "current",
    legalScope: "dora",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-acpr-dsp2-api-2025",
    title: "ACPR : notifier un probleme affectant une API DSP2",
    authority: "acpr",
    url: "https://acpr.banque-france.fr/fr/professionnels/vos-outils-et-services/notifier-lacpr-un-probleme-affectant-une-api",
    checkedAt: "2026-06-04",
    sourceVersion: "acpr-dsp2-api-2025",
    verifiedAt: "2026-06-04T09:38:00.000Z",
    contentHash: "acpr-dsp2-api-v24",
    summary:
      "Reference de prudence pour les futurs connecteurs open banking : la V2.4 reste en simulation pedagogique.",
    linkedRuleIds: ["rule-bank-import-demo-2026-v1", "rule-regulatory-controls-2026-v1"],
    lastControlAt: "2026-06-04T09:44:00.000Z",
    snapshotStatus: "current",
    legalScope: "dsp2",
    reliability: "official",
    status: "active",
  },
  {
    id: "src-anssi-hygiene-2017",
    title: "ANSSI : guide d'hygiene informatique",
    authority: "anssi",
    url: "https://cyber.gouv.fr/publications/guide-dhygiene-informatique",
    checkedAt: "2026-06-04",
    sourceVersion: "anssi-hygiene-2017-control-2026",
    verifiedAt: "2026-06-04T09:40:00.000Z",
    contentHash: "anssi-hygiene-v24",
    summary:
      "Socle de mesures de securite pour cadrer la demo avant stockage documentaire ou connecteurs reels.",
    linkedRuleIds: ["rule-cyber-hygiene-demo-2026-v1"],
    lastControlAt: "2026-06-04T09:46:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "cyber",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-anssi-backup-2023",
    title: "ANSSI : fondamentaux de la sauvegarde des systemes d'information",
    authority: "anssi",
    url: "https://cyber.gouv.fr/publications/fondamentaux-sauvegarde-systemes-dinformation",
    checkedAt: "2026-06-04",
    sourceVersion: "anssi-backup-2023-control-2026",
    verifiedAt: "2026-06-04T09:41:00.000Z",
    contentHash: "anssi-backup-v24",
    summary:
      "Bonnes pratiques de sauvegarde mentionnees dans la roadmap avant tout stockage documentaire reel.",
    linkedRuleIds: ["rule-cyber-hygiene-demo-2026-v1"],
    lastControlAt: "2026-06-04T09:47:00.000Z",
    snapshotStatus: "to-review",
    legalScope: "cyber",
    reliability: "official",
    status: "to-review",
  },
  {
    id: "src-eurlex-atad-2016-1164",
    title: "EUR-Lex : directive ATAD 2016/1164",
    authority: "eurlex",
    url: "https://eur-lex.europa.eu/eli/dir/2016/1164/oj",
    checkedAt: "2026-06-04",
    sourceVersion: "eurlex-atad-2016-1164",
    verifiedAt: "2026-06-04T09:42:00.000Z",
    contentHash: "eurlex-atad-v24",
    summary:
      "Reference europeenne pour signaux internationaux hors MVP et revue avocat fiscaliste.",
    linkedRuleIds: ["rule-manual-review-complexity-2026-v1"],
    lastControlAt: "2026-06-04T09:48:00.000Z",
    snapshotStatus: "current",
    legalScope: "atad",
    reliability: "official",
    status: "active",
  },
];

export const sourceSnapshots: SourceSnapshot[] = evidenceSources.map((source) => ({
  id: `snapshot-${source.id}`,
  sourceId: source.id,
  sourceVersion: source.sourceVersion,
  capturedAt: source.verifiedAt,
  contentHash: source.contentHash,
  summary: source.summary,
  linkedRuleIds: source.linkedRuleIds,
  status: source.snapshotStatus,
}));

export function getEvidenceSource(id: string) {
  return evidenceSources.find((source) => source.id === id);
}

export function getSourceSnapshot(sourceId: string) {
  return sourceSnapshots.find((snapshot) => snapshot.sourceId === sourceId);
}
